[package]
name = "cs220"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
etrace = "1.1.1"
itertools = "0.10.5"
lazy_static = "1.4.0"
pest = "2.5.1"
pest_derive = "2.5.1"
rayon = "1.6.0"
